# Generated by Django 3.1.1 on 2020-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=30, null=True)),
                ('desc_prod', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.CharField(blank=True, max_length=10, null=True)),
                ('foto_prod', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
    ]
